[tox]
isolated_build = True
envlist =
    py311
    py312
    py313
    py314
    py315

[testenv]
deps =
    pytest
    pytest-cov
commands =
    python -m pytest --cov=datedelta --cov-fail-under=100 --doctest-glob='*.rst' {posargs}
